---
title: "Network inference with LIMITS"
author:
  - Mariam Rahali Masbouri
date: today 
format:
  html:
    page-layout: full
    code-fold: true
    toc: true
    toc-location: left
    theme: cosmo
    number-sections: true
    embed-resources: true
execute:
  cache: false 
  warning: false
project:
  execute-dir: project
editor: source
editor_options: 
  chunk_output_type: inline
---

In this section, we will apply LIMITS to the IBD cohort only (since it is the only cohort that has enough time points to apply the method).

## IBD cohort

> A sample (starting with H) has a taxon with relative abundance == 1.

We first import the IBD dataset from the MAE object in the chunk code below.

```{r}

tmp <-
  mae[["IBD"]] |>
  assay() |>
  t() |>
  as.data.frame() |>
  rownames_to_column("uid") |>
  pivot_longer(-uid, names_to = "taxon", values_to = "rel_ab") |>
  left_join(
    mae[["IBD"]] |> colData() |> as_tibble(rownames = "uid") |> select(uid, pid, visit_num, diagnosis),
    by = join_by(uid)
  )

```

```{r}

tmp_healthy <- tmp |> filter(diagnosis == "nonIBD")
tmp_diseased <- tmp |> filter(diagnosis == "UC" | diagnosis == "CD")

```


```{r}

# res <- run_limits_bootstrap(healthy_df, n_bootstrap = 1, subsample_pcts = 0.4, max_attempts = 5, bagging.iter = 5)

```

```{r}

# df_res <- get_limits_results(res)

```

